Repository grommet/grommet, pull requests merged in 2018-12, with the labels that each got.

#2508 Improve SSR by trying to guess device width using mobile-detect
  package.json
  src/js/components/Grommet/Grommet.js
  src/js/components/Grommet/README.md
  src/js/components/Grommet/__tests__/Grommet-test.js
  src/js/components/Grommet/__tests__/__snapshots__/Grommet-test.js.snap
  src/js/components/Grommet/doc.js
  src/js/components/Grommet/index.d.ts
  src/js/components/__tests__/__snapshots__/README-test.js.snap
  src/js/components/__tests__/__snapshots__/typescript-test.js.snap
  src/js/themes/base.js
  src/js/utils/responsive.js
  yarn.lock
Labels: in progress

#2511 TextInput doc theme
  src/js/components/TextInput/README.md
  src/js/components/TextInput/StyledTextInput.js
  src/js/components/TextInput/doc.js
  src/js/components/__tests__/__snapshots__/README-test.js.snap
Labels: in progress

#2512 Improve typescript support for some Components having true or false values in props
  src/js/components/Box/README.md
  src/js/components/Box/doc.js
  src/js/components/Box/index.d.ts
  src/js/components/Grid/README.md
  src/js/components/Grid/doc.js
  src/js/components/Grid/index.d.ts
  src/js/components/Tabs/README.md
  src/js/components/Tabs/doc.js
  src/js/components/Tabs/index.d.ts
  src/js/components/TextArea/README.md
  src/js/components/TextArea/doc.js
  src/js/components/TextArea/index.d.ts
  src/js/components/__tests__/__snapshots__/README-test.js.snap
  src/js/components/__tests__/__snapshots__/typescript-test.js.snap
Labels: in progress

#2504 Changed InfiniteScroll to fix an issue with refs. Changed Select to use InfiniteScroll replace.
  package.json
  src/js/components/CheckBox/CheckBox.js
  src/js/components/DropButton/DropButton.js
  src/js/components/Grommet/Grommet.js
  src/js/components/InfiniteScroll/InfiniteScroll.js
  src/js/components/InfiniteScroll/__tests__/__snapshots__/InfiniteScroll-test.js.snap
  src/js/components/InfiniteScroll/infinitescroll.stories.js
  src/js/components/Layer/Layer.js
  src/js/components/Select/SelectContainer.js
  src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
  src/js/components/Select/stories/select.stories.js
  yarn.lock
Labels: in progress

#2518 Fixed an issue with InfiniteScroll replace indexing
  src/js/components/InfiniteScroll/InfiniteScroll.js
Labels: in progress

#2519 Improved checkbox theme extend
  src/js/components/CheckBox/CheckBox.js
  src/js/components/CheckBox/__tests__/__snapshots__/CheckBox-test.js.snap
  src/js/components/CheckBox/checkbox.stories.js
Labels: in progress

#2524 Update react-desc dependency and TS definitions for optional shape properties
  package.json
  src/js/components/Accordion/index.d.ts
  src/js/components/Anchor/index.d.ts
  src/js/components/Box/index.d.ts
  src/js/components/Button/index.d.ts
  src/js/components/Calendar/index.d.ts
  src/js/components/Carousel/index.d.ts
  src/js/components/Chart/index.d.ts
  src/js/components/Clock/index.d.ts
  src/js/components/DataTable/index.d.ts
  src/js/components/Diagram/index.d.ts
  src/js/components/Distribution/index.d.ts
  src/js/components/Drop/index.d.ts
  src/js/components/DropButton/index.d.ts
  src/js/components/Grid/index.d.ts
  src/js/components/Heading/index.d.ts
  src/js/components/Image/index.d.ts
  src/js/components/Layer/index.d.ts
  src/js/components/Menu/index.d.ts
  src/js/components/Meter/index.d.ts
  src/js/components/Paragraph/index.d.ts
  src/js/components/RangeSelector/index.d.ts
  src/js/components/Select/index.d.ts
  src/js/components/SkipLinks/index.d.ts
  src/js/components/Stack/index.d.ts
  src/js/components/Table/index.d.ts
  src/js/components/Tabs/index.d.ts
  src/js/components/Text/index.d.ts
  src/js/components/TextInput/index.d.ts
  src/js/components/Video/index.d.ts
  src/js/components/WorldMap/index.d.ts
  src/js/components/__tests__/__snapshots__/typescript-test.js.snap
  yarn.lock
Labels: in progress

#2526 Fix for #2458
  src/js/components/RangeSelector/RangeSelector.js
Labels: in progress

#2528 WIP Box Improvements
  src/js/components/Box/Box.js
  src/js/components/hocs.js
Labels: in progress

#2523 Fixed component warnings
  src/js/components/Anchor/README.md
  src/js/components/Anchor/doc.js
  src/js/components/Anchor/index.d.ts
  src/js/components/Button/README.md
  src/js/components/Button/doc.js
  src/js/components/Button/index.d.ts
  src/js/components/DataTable/DataTable.js
  src/js/components/Diagram/README.md
  src/js/components/Diagram/doc.js
  src/js/components/Diagram/index.d.ts
  src/js/components/Drop/DropContainer.js
  src/js/components/Heading/README.md
  src/js/components/Heading/doc.js
  src/js/components/Heading/index.d.ts
  src/js/components/Paragraph/README.md
  src/js/components/Paragraph/doc.js
  src/js/components/Paragraph/index.d.ts
  src/js/components/RangeSelector/README.md
  src/js/components/RangeSelector/doc.js
  src/js/components/RangeSelector/index.d.ts
  src/js/components/Select/SelectContainer.js
  src/js/components/Text/README.md
  src/js/components/Text/doc.js
  src/js/components/Text/index.d.ts
  src/js/components/WorldMap/README.md
  src/js/components/WorldMap/doc.js
  src/js/components/WorldMap/index.d.ts
  src/js/components/__tests__/__snapshots__/README-test.js.snap
  src/js/components/__tests__/__snapshots__/components-test.js.snap
  src/js/components/__tests__/__snapshots__/typescript-test.js.snap
  src/js/utils/prop-types.js
Labels: in progress

#2530 Fixed storybook complaning about missing path.
  src/js/components/Box/Box.js
  src/js/components/hocs.js
Labels: in progress

#2534 Fixed regression with Layer margin.
  src/js/components/Layer/StyledLayer.js
  src/js/components/Layer/__tests__/__snapshots__/Layer-test.js.snap
  src/js/components/Layer/layer.stories.js
Labels: in progress

#2525 Add intrinsic elements to non polymorphic components
  src/js/components/Anchor/README.md
  src/js/components/Anchor/doc.js
  src/js/components/Anchor/index.d.ts
  src/js/components/Button/README.md
  src/js/components/Button/doc.js
  src/js/components/Button/index.d.ts
  src/js/components/Image/README.md
  src/js/components/Image/doc.js
  src/js/components/Image/index.d.ts
  src/js/components/Paragraph/README.md
  src/js/components/Paragraph/doc.js
  src/js/components/Paragraph/index.d.ts
  src/js/components/Table/README.md
  src/js/components/Table/doc.js
  src/js/components/Table/index.d.ts
  src/js/components/TableBody/README.md
  src/js/components/TableBody/doc.js
  src/js/components/TableBody/index.d.ts
  src/js/components/TableCell/README.md
  src/js/components/TableCell/doc.js
  src/js/components/TableCell/index.d.ts
  src/js/components/TableFooter/README.md
  src/js/components/TableFooter/doc.js
  src/js/components/TableFooter/index.d.ts
  src/js/components/TableHeader/README.md
  src/js/components/TableHeader/doc.js
  src/js/components/TableHeader/index.d.ts
  src/js/components/TableRow/README.md
  src/js/components/TableRow/doc.js
  src/js/components/TableRow/index.d.ts
  src/js/components/Text/README.md
  src/js/components/Text/doc.js
  src/js/components/Text/index.d.ts
  src/js/components/TextArea/README.md
  src/js/components/TextArea/doc.js
  src/js/components/TextArea/index.d.ts
  src/js/components/TextInput/README.md
  src/js/components/TextInput/doc.js
  src/js/components/TextInput/index.d.ts
  src/js/components/__tests__/__snapshots__/README-test.js.snap
  src/js/components/__tests__/__snapshots__/components-test.js.snap
  src/js/components/__tests__/__snapshots__/typescript-test.js.snap
  tools/generate-readme-ts.js
Labels: in progress

#2544 [Markdown] Style anchors
  src/js/components/Markdown/Markdown.js
  src/js/components/Markdown/__tests__/Markdown-test.js
  src/js/components/Markdown/__tests__/__snapshots__/Markdown-test.js.snap
Labels: in progress

#2532 [Select] Add option to limit height of the drop container
  src/js/components/Select/README.md
  src/js/components/Select/SelectContainer.js
  src/js/components/Select/__tests__/Select-test.js
  src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
  src/js/components/Select/doc.js
  src/js/components/Select/index.d.ts
  src/js/components/Select/stories/select.stories.js
  src/js/components/__tests__/__snapshots__/README-test.js.snap
  src/js/components/__tests__/__snapshots__/components-test.js.snap
  src/js/components/__tests__/__snapshots__/typescript-test.js.snap
Labels: in progress

#2548 Fix install instructions
  README.md
Labels: in progress

#2541 Changed Select to add target when selecting an option.
  src/js/components/Select/Select.js
  src/js/components/Select/SelectContainer.js
Labels: in progress

#2546 Add empty option to select
  src/js/components/Select/README.md
  src/js/components/Select/SelectContainer.js
  src/js/components/Select/__tests__/Select-test.js
  src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
  src/js/components/Select/doc.js
  src/js/components/Select/index.d.ts
  src/js/components/Select/stories/select.stories.js
  src/js/components/__tests__/__snapshots__/README-test.js.snap
  src/js/components/__tests__/__snapshots__/components-test.js.snap
  src/js/components/__tests__/__snapshots__/typescript-test.js.snap
Labels: in progress

#2550 Select - Object Multiple story
  src/js/components/Select/stories/select.stories.js
Labels: in progress

#2555 Fixed accessibility for Checkbox
  src/js/components/CheckBox/CheckBox.js
  src/js/components/CheckBox/StyledCheckBox.js
  src/js/components/CheckBox/__tests__/__snapshots__/CheckBox-test.js.snap
Labels: in progress

#2553 Changed Select to fix an issue with scrolling and keyboard navigation
  src/js/components/Layer/layer.stories.js
  src/js/utils/DOM.js
Labels: in progress

#2551 Updated base theme colors.
  src/js/components/Accordion/__tests__/__snapshots__/Accordion-test.js.snap
  src/js/components/Accordion/accordion.stories.js
  src/js/components/AccordionPanel/AccordionPanel.js
  src/js/components/Anchor/__tests__/__snapshots__/Anchor-test.js.snap
  src/js/components/Box/__tests__/__snapshots__/Box-test.js.snap
  src/js/components/Button/__tests__/Button-test.js
  src/js/components/Button/__tests__/__snapshots__/Button-test.js.snap
  src/js/components/Chart/__tests__/__snapshots__/Chart-test.js.snap
  src/js/components/Clock/__tests__/__snapshots__/Clock-test.js.snap
  src/js/components/Collapsible/collapsible.stories.js
  src/js/components/Diagram/__tests__/__snapshots__/Diagram-test.js.snap
  src/js/components/Drop/drop.stories.js
  src/js/components/FormField/__tests__/__snapshots__/FormField-test.js.snap
  src/js/components/Grid/grid.stories.js
  src/js/components/Layer/layer.stories.js
  src/js/components/Markdown/__tests__/__snapshots__/Markdown-test.js.snap
  src/js/components/Meter/__tests__/__snapshots__/Meter-test.js.snap
  src/js/components/RadioButton/radiobutton.stories.js
  src/js/components/RangeSelector/RangeSelector.js
  src/js/components/RangeSelector/__tests__/__snapshots__/RangeSelector-test.js.snap
  src/js/components/RoutedAnchor/__tests__/__snapshots__/RoutedAnchor-test.js.snap
  src/js/components/SkipLinks/__tests__/__snapshots__/SkipLink-test.js.snap
  src/js/components/Tabs/tabs.stories.js
  src/js/components/Text/__tests__/__snapshots__/Text-test.js.snap
  src/js/components/Video/StyledVideo.js
  src/js/components/Video/Video.js
  src/js/components/Video/__tests__/__snapshots__/Video-test.js.snap
  src/js/components/WorldMap/__tests__/__snapshots__/WorldMap-test.js.snap
  src/js/themes/__tests__/__snapshots__/theme-test.js.snap
  src/js/themes/__tests__/theme-test.js
  src/js/themes/base.js
  src/js/themes/grommet.js
  src/js/utils/background.js
Labels: in progress

#2558 Fixed some incorrect color values
  src/js/components/Box/__tests__/__snapshots__/Box-test.js.snap
  src/js/components/FormField/__tests__/__snapshots__/FormField-test.js.snap
  src/js/components/Text/__tests__/__snapshots__/Text-test.js.snap
  src/js/themes/__tests__/__snapshots__/theme-test.js.snap
  src/js/themes/base.js
Labels: in progress

#2557 move to grommet-icons v4
  package.json
  src/js/components/Accordion/__tests__/__snapshots__/Accordion-test.js.snap
  src/js/components/Box/Box.js
  src/js/components/Box/StyledBox.js
  src/js/components/Box/__tests__/__snapshots__/Box-test.js.snap
  src/js/components/Calendar/__tests__/__snapshots__/Calendar-test.js.snap
  src/js/components/Carousel/__tests__/__snapshots__/Carousel-test.js.snap
  src/js/components/Collapsible/Collapsible.js
  src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
  src/js/components/Drop/DropContainer.js
  src/js/components/Grommet/Grommet.js
  src/js/components/Layer/LayerContainer.js
  src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap
  src/js/components/RangeSelector/RangeSelector.js
  src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
  src/js/components/Video/Video.js
  src/js/components/Video/__tests__/__snapshots__/Video-test.js.snap
  src/js/components/hocs.js
  src/js/themes/__tests__/__snapshots__/theme-test.js.snap
  src/js/themes/base.js
  yarn.lock
Labels: in progress

#2560 Added onMore story for InfiniteScroll
  src/js/components/InfiniteScroll/infinitescroll.stories.js
Labels: in progress

#2561 grommet-styles and grommet-icons removed as peerDependency
  .babelrc
  README.md
  package.json
  src/js/themes/base.js
  yarn.lock
Labels: in progress

#2540 Added MaskedInput
  src/js/components/MaskedInput/MaskedInput.js
  src/js/components/MaskedInput/README.md
  src/js/components/MaskedInput/StyledMaskedInput.js
  src/js/components/MaskedInput/__tests__/MaskedInput-test.js
  src/js/components/MaskedInput/__tests__/__snapshots__/MaskedInput-test.js.snap
  src/js/components/MaskedInput/doc.js
  src/js/components/MaskedInput/index.d.ts
  src/js/components/MaskedInput/index.js
  src/js/components/MaskedInput/maskedinput.stories.js
  src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
  src/js/components/TextArea/StyledTextArea.js
  src/js/components/TextInput/StyledTextInput.js
  src/js/components/TextInput/__tests__/__snapshots__/TextInput-test.js.snap
  src/js/components/__tests__/__snapshots__/README-test.js.snap
  src/js/components/__tests__/__snapshots__/components-test.js.snap
  src/js/components/__tests__/__snapshots__/typescript-test.js.snap
  src/js/components/index.js
  src/js/utils/styles.js
Labels: enhancement, in progress

#2543 Skiplinks fix to allow accessibility
  src/js/components/FocusedContainer.js
  src/js/components/Layer/LayerContainer.js
  src/js/components/SkipLinks/SkipLinks.js
  src/js/components/__tests__/__snapshots__/FocusedContainer-test.js.snap
Labels: in progress

#2562 Cleaned up stories to be more visually appealing
  src/js/components/Anchor/anchor.stories.js
  src/js/components/Button/button.stories.js
  src/js/components/Calendar/calendar.stories.js
  src/js/components/Carousel/carousel.stories.js
  src/js/components/Chart/chart.stories.js
  src/js/components/CheckBox/checkbox.stories.js
  src/js/components/Clock/clock.stories.js
  src/js/components/DataTable/datatable.stories.js
  src/js/components/Diagram/diagram.stories.js
  src/js/components/DropButton/dropbutton.stories.js
  src/js/components/FormField/formfield.stories.js
  src/js/components/Markdown/markdown.stories.js
  src/js/components/MaskedInput/maskedinput.stories.js
  src/js/components/Menu/menu.stories.js
  src/js/components/Meter/meter.stories.js
  src/js/components/RadioButton/radiobutton.stories.js
  src/js/components/RangeInput/rangeinput.stories.js
  src/js/components/RangeSelector/rangeselector.stories.js
  src/js/components/Table/table.stories.js
  src/js/components/TextArea/textarea.stories.js
  src/js/components/TextInput/textinput.stories.js
  src/js/components/Video/video.stories.js
  src/js/components/WorldMap/worldmap.stories.js
Labels: in progress

#2568 Changed Select to fix an issue with rendering option state
  src/js/components/Select/SelectContainer.js
  src/js/components/Select/SelectOption.js
  src/js/components/Select/stories/select.stories.js
Labels: in progress

#2569 Added temporary withTheme proxy.
  src/js/components/hocs.js
Labels: in progress

#2570 Added fix for dropHeight in Select to use max height instead of height.
  src/js/components/MaskedInput/__tests__/MaskedInput-test.js
  src/js/components/Select/SelectContainer.js
  src/js/components/Select/StyledSelect.js
  src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
Labels: in progress

#2566 Layer - to allow corner options
  src/js/components/Layer/README.md
  src/js/components/Layer/StyledLayer.js
  src/js/components/Layer/doc.js
  src/js/components/Layer/index.d.ts
  src/js/components/Layer/layer.stories.js
  src/js/components/__tests__/__snapshots__/README-test.js.snap
  src/js/components/__tests__/__snapshots__/typescript-test.js.snap
Labels: enhancement, in progress

#2567 Menu - theme docs
  src/js/components/Menu/README.md
  src/js/components/Menu/doc.js
  src/js/components/__tests__/__snapshots__/README-test.js.snap
Labels: documentation :memo:, in progress

#2580 Changed Select to fix an issue with scrolling while keyboard navigating.
  src/js/components/Select/SelectContainer.js
  src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
Labels: in progress

#2576 Added an example and doc of component overrides in markdown
  src/js/components/Markdown/Markdown.js
  src/js/components/Markdown/README.md
  src/js/components/Markdown/doc.js
  src/js/components/Markdown/index.d.ts
  src/js/components/Markdown/markdown.stories.js
  src/js/components/__tests__/__snapshots__/README-test.js.snap
  src/js/components/__tests__/__snapshots__/typescript-test.js.snap
Labels: in progress

#2579 Layer - theme docs
  src/js/components/Layer/README.md
  src/js/components/Layer/doc.js
  src/js/components/__tests__/__snapshots__/README-test.js.snap
Labels: in progress

#2583 typescript updates
  src/js/components/Accordion/index.d.ts
  src/js/components/Anchor/index.d.ts
  src/js/components/Button/index.d.ts
  src/js/components/Calendar/index.d.ts
  src/js/components/Chart/index.d.ts
  src/js/components/CheckBox/index.d.ts
  src/js/components/Clock/index.d.ts
  src/js/components/DataTable/index.d.ts
  src/js/components/Distribution/index.d.ts
  src/js/components/Drop/index.d.ts
  src/js/components/DropButton/index.d.ts
  src/js/components/InfiniteScroll/index.d.ts
  src/js/components/Keyboard/index.d.ts
  src/js/components/Layer/index.d.ts
  src/js/components/MaskedInput/index.d.ts
  src/js/components/Meter/index.d.ts
  src/js/components/RadioButton/index.d.ts
  src/js/components/RangeInput/index.d.ts
  src/js/components/RangeSelector/index.d.ts
  src/js/components/Select/index.d.ts
  src/js/components/Tabs/index.d.ts
  src/js/components/TextArea/index.d.ts
  src/js/components/TextInput/index.d.ts
  src/js/components/WorldMap/index.d.ts
  src/js/components/__tests__/__snapshots__/typescript-test.js.snap
  yarn.lock
Labels: in progress

#2586 Changed TextInput to add dropHeight
  src/js/components/Select/README.md
  src/js/components/Select/doc.js
  src/js/components/Select/index.d.ts
  src/js/components/TextInput/README.md
  src/js/components/TextInput/TextInput.js
  src/js/components/TextInput/__tests__/TextInput-test.js
  src/js/components/TextInput/__tests__/__snapshots__/TextInput-test.js.snap
  src/js/components/TextInput/doc.js
  src/js/components/TextInput/index.d.ts
  src/js/components/TextInput/textinput.stories.js
  src/js/components/__tests__/__snapshots__/README-test.js.snap
  src/js/components/__tests__/__snapshots__/components-test.js.snap
  src/js/components/__tests__/__snapshots__/typescript-test.js.snap
Labels: in progress

#2588 Docs/theme collapsible
  src/js/components/Collapsible/README.md
  src/js/components/Collapsible/doc.js
  src/js/components/__tests__/__snapshots__/README-test.js.snap
Labels: in progress

#2592 Updated component descriptions
  src/js/components/Box/README.md
  src/js/components/Box/doc.js
  src/js/components/Button/README.md
  src/js/components/Button/doc.js
  src/js/components/Calendar/README.md
  src/js/components/Calendar/doc.js
  src/js/components/Collapsible/README.md
  src/js/components/Collapsible/doc.js
  src/js/components/Diagram/README.md
  src/js/components/Diagram/doc.js
  src/js/components/Distribution/README.md
  src/js/components/Distribution/doc.js
  src/js/components/Drop/README.md
  src/js/components/Drop/doc.js
  src/js/components/DropButton/README.md
  src/js/components/DropButton/doc.js
  src/js/components/FormField/README.md
  src/js/components/FormField/doc.js
  src/js/components/Grid/README.md
  src/js/components/Grid/doc.js
  src/js/components/Grommet/README.md
  src/js/components/Grommet/doc.js
  src/js/components/Keyboard/README.md
  src/js/components/Keyboard/doc.js
  src/js/components/Layer/README.md
  src/js/components/Layer/doc.js
  src/js/components/Menu/README.md
  src/js/components/Menu/doc.js
  src/js/components/RangeInput/README.md
  src/js/components/RangeInput/doc.js
  src/js/components/RangeSelector/README.md
  src/js/components/RangeSelector/doc.js
  src/js/components/Select/README.md
  src/js/components/Select/doc.js
  src/js/components/Stack/README.md
  src/js/components/Stack/doc.js
  src/js/components/Tabs/README.md
  src/js/components/Tabs/doc.js
  src/js/components/TextArea/README.md
  src/js/components/TextArea/doc.js
  src/js/components/TextInput/README.md
  src/js/components/TextInput/doc.js
  src/js/components/__tests__/__snapshots__/README-test.js.snap
  src/js/components/__tests__/__snapshots__/components-test.js.snap
Labels: in progress

#2596 Tests cleanups
  src/js/components/RadioButton/__tests__/RadioButton-test.js
  src/js/components/RadioButton/__tests__/__snapshots__/RadioButton-test.js.snap
  src/js/components/Tabs/__tests__/Tabs-test.js
  src/js/components/Tabs/__tests__/__snapshots__/Tabs-test.js.snap
Labels: in progress

#2591 Changed Grommet to clear body margin when full
  src/js/components/Grommet/Grommet.js
Labels: in progress

#2599 Layer - add theme background
  src/js/components/Layer/README.md
  src/js/components/Layer/doc.js
  src/js/components/__tests__/__snapshots__/README-test.js.snap
Labels: in progress

#2603 Enables px value for size in Box's round prop
  src/js/components/Box/StyledBox.js
  src/js/components/Box/box.stories.js
Labels: in progress

#2605 [Meter] fix bug not allowing to set custom thickness size
  src/js/components/Meter/Bar.js
  src/js/components/Meter/Circle.js
  src/js/components/Meter/__tests__/Meter-test.js
  src/js/components/Meter/__tests__/__snapshots__/Meter-test.js.snap
Labels: in progress

#2607 Add ability to configure font-weight by heading level in the theme
  src/js/components/Heading/StyledHeading.js
  src/js/components/Heading/__tests__/Heading-test.js
  src/js/components/Heading/__tests__/__snapshots__/Heading-test.js.snap
  src/js/themes/base.js
Labels: in progress

#2604 Add border-style to box component
  src/js/components/Box/README.md
  src/js/components/Box/StyledBox.js
  src/js/components/Box/__tests__/Box-test.js
  src/js/components/Box/__tests__/__snapshots__/Box-test.js.snap
  src/js/components/Box/box.stories.js
  src/js/components/Box/doc.js
  src/js/components/Box/index.d.ts
  src/js/components/__tests__/__snapshots__/README-test.js.snap
  src/js/components/__tests__/__snapshots__/components-test.js.snap
  src/js/components/__tests__/__snapshots__/typescript-test.js.snap
Labels: in progress

#2601 Added findDOMNode back for infinite scroll.
  src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
  src/js/components/InfiniteScroll/InfiniteScroll.js
  src/js/components/InfiniteScroll/infinitescroll.stories.js
  src/js/components/MaskedInput/__tests__/MaskedInput-test.js
Labels: in progress

#2587 allowing Layer a custom animation
  src/js/components/Layer/README.md
  src/js/components/Layer/StyledLayer.js
  src/js/components/Layer/__tests__/__snapshots__/Layer-test.js.snap
  src/js/components/Layer/doc.js
  src/js/components/Layer/index.d.ts
  src/js/components/__tests__/__snapshots__/README-test.js.snap
  src/js/components/__tests__/__snapshots__/typescript-test.js.snap
Labels: in progress

#2520 Added Form
  package.json
  src/js/components/Button/Button.js
  src/js/components/Button/__tests__/__snapshots__/Button-test.js.snap
  src/js/components/Calendar/__tests__/__snapshots__/Calendar-test.js.snap
  src/js/components/Carousel/__tests__/__snapshots__/Carousel-test.js.snap
  src/js/components/DropButton/__tests__/__snapshots__/DropButton-test.js.snap
  src/js/components/Form/Form.js
  src/js/components/Form/FormContext.js
  src/js/components/Form/README.md
  src/js/components/Form/__tests__/Form-test.js
  src/js/components/Form/__tests__/__snapshots__/Form-test.js.snap
  src/js/components/Form/doc.js
  src/js/components/Form/form.stories.js
  src/js/components/Form/index.d.ts
  src/js/components/Form/index.js
  src/js/components/FormField/FormField.js
  src/js/components/FormField/README.md
  src/js/components/FormField/__tests__/__snapshots__/FormField-test.js.snap
  src/js/components/FormField/doc.js
  src/js/components/FormField/index.d.ts
  src/js/components/RoutedButton/__tests__/__snapshots__/RoutedButton-test.js.snap
  src/js/components/Video/__tests__/__snapshots__/Video-test.js.snap
  src/js/components/__tests__/__snapshots__/README-test.js.snap
  src/js/components/__tests__/__snapshots__/components-test.js.snap
  src/js/components/__tests__/__snapshots__/typescript-test.js.snap
  src/js/components/index.js
  yarn.lock
Labels: enhancement, in progress
