Repository grommet/grommet, pull requests merged in 2019-10, with the labels that each got.

#3382 TypeScript Box border - Adding reusable types
  src/js/components/Box/index.d.ts
Labels: typescript

#3368 Adjust Heading/Responsive Context Grommet docs
  src/js/components/Heading/README.md
  src/js/components/Heading/doc.js
  src/js/components/__tests__/__snapshots__/README-test.js.snap
  src/js/contexts/ResponsiveContext/doc.js
Labels: waiting

#3363 Fix range selector step issue
  src/js/components/RangeSelector/RangeSelector.js
  src/js/components/RangeSelector/__tests__/RangeSelector-test.js
  src/js/components/RangeSelector/__tests__/__snapshots__/RangeSelector-test.js.snap
Labels: waiting

#3358 Added TS handlers for onChange
  src/js/components/CheckBox/index.d.ts
  src/js/components/Clock/index.d.ts
  src/js/components/Form/index.d.ts
  src/js/components/MaskedInput/index.d.ts
  src/js/components/RadioButton/index.d.ts
  src/js/components/RadioButtonGroup/index.d.ts
  src/js/components/RangeInput/index.d.ts
  src/js/components/RangeSelector/index.d.ts
  src/js/components/Select/index.d.ts
  src/js/components/TextArea/index.d.ts
Labels: waiting

#3399 Refactor Components/All story to hooks
  src/js/allcomponents.stories.js
Labels: waiting

#3403 Convert SkipLinks component to Hooks
  src/js/components/SkipLinks/SkipLinks.js
Labels: waiting

#3439 update contribution docs
  CONTRIBUTING.md
Labels: waiting

#3346 Added Box types to tableCell to accept
  src/js/components/Box/index.d.ts
  src/js/components/TableCell/index.d.ts
Labels: waiting

#3424 Refactor Calendar stories and Custom TextInput to use Hooks
  src/js/components/Calendar/stories/CustomHeader.js
  src/js/components/Calendar/stories/CustomSizeHeading.js
  src/js/components/Calendar/stories/Dual.js
  src/js/components/Calendar/stories/Simple.js
  src/js/components/TextInput/stories/Custom.js
Labels: waiting

#3415 Refactoring AccordionPanel to use hooks
  src/js/components/AccordionPanel/AccordionPanel.js
Labels: waiting

#3491 Add eslint-plugin-react-hooks
  .eslintrc
  package.json
  yarn.lock
Labels: discussion

#3469 Changed Chart to add auto width and gap
  src/js/components/Chart/Chart.js
  src/js/components/Chart/README.md
  src/js/components/Chart/__tests__/Chart-test.js
  src/js/components/Chart/__tests__/__snapshots__/Chart-test.js.snap
  src/js/components/Chart/doc.js
  src/js/components/Chart/index.d.ts
  src/js/components/Chart/stories/Layout.js
  src/js/components/Chart/stories/Simple.js
  src/js/components/Meter/Meter.js
  src/js/components/__tests__/__snapshots__/README-test.js.snap
  src/js/components/__tests__/__snapshots__/components-test.js.snap
  storybook/theme.js
Labels: waiting
