Repository grommet/grommet, pull requests merged in 2023-09, with the labels that each got.

#6097 Fix drop container transform
  src/js/components/Drop/DropContainer.js
  src/js/components/Grommet/index.d.ts
  src/js/components/Grommet/propTypes.js
Labels: needs attention, PRty

#6943 Fixed DataFilters to show all filter options
  src/js/components/Data/__tests__/Data-test.tsx
  src/js/components/Data/__tests__/__snapshots__/Data-test.tsx.snap
  src/js/components/DataFilters/DataFilters.js
  src/js/components/DataFilters/__tests__/DataFilters-test.tsx
  src/js/components/DataFilters/__tests__/__snapshots__/DataFilters-test.tsx.snap
Labels: Data and friends

#6887 Disabled the header checkbox to (un)select all lines in DataTable
  src/js/components/DataTable/DataTable.js
  src/js/components/DataTable/Header.js
  src/js/components/DataTable/__tests__/DataTable-test.tsx
  src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.tsx.snap
  src/js/components/DataTable/index.d.ts
  src/js/components/DataTable/propTypes.js
  src/js/components/DataTable/stories/AllowSelectAll.js
Labels: PRty
