Repository grommet/grommet, pull requests merged in 2023-03, with the labels that each got.

#6690 Update status-error color to fix Form/AggregateValidation a11y violation
  src/js/components/Grommet/__tests__/__snapshots__/Grommet-test.js.snap
  src/js/components/__tests__/__snapshots__/components-test.js.snap
  src/js/themes/base.js
Labels: needs attention, accessibility

#5943 Trigger validation using Form Field
  src/js/components/Form/Form.js
  src/js/components/Form/__tests__/Form-test-controlled.js
  src/js/components/Form/stories/TriggerValidationUsingFormField.js
  src/js/components/FormField/FormField.js
  src/js/components/FormField/index.d.ts
  src/js/components/FormField/propTypes.js
  src/js/components/__tests__/__snapshots__/components-test.js.snap
Labels: PRty

#6391 Fix file input focus traversal
  src/js/components/FileInput/FileInput.js
  src/js/components/FileInput/__tests__/__snapshots__/FileInput-test.tsx.snap
Labels: PRty

#6642 add support for border between in border array
  src/js/components/Box/Box.js
  src/js/components/Box/stories/Border.js
Labels: PRty

#6687 Fixed Type Error in List Component
  src/js/components/List/index.d.ts
Labels: typescript, PRty
